#!/usr/local/bin/python3

import cgitb
import cgi
cgitb.enable()

strForm='<form action="/cgi/storage"><input type="text" name="name" value="ruibz" /> <input type="text" name="name" value="haoyingl" /><input type="submit" value="Submit"></form>'

print("Content-Type: text/html")    # HTML is following
print()
print("<a href='http://www.baidu.com'>Hello World</a>")
print(strForm)


""

