#!/usr/local/bin/python3

import cgitb
import cgi
import os
cgitb.enable()

urlField = cgi.FieldStorage()

strForm='<form action="/cgi/search">keyword 1:<input type="text" name="keyword" value="" /> keyword 2:<input type="text" name="keyword" value="" /><input type="submit" value="Submit"></form>'

print("Content-Type: text/html")
print()
print(strForm)

def getSearchResult(keys):
    table = []
    with open(os.path.join('cgi', 'test.txt')) as f:
        lines = f.readlines()
        for line in lines :
            items = line.split(' ')
            table.append(items)

    return table

table = getSearchResult(urlField.getvalue('keyword'))

strStyle = open(os.path.join('cgi', 'style.css')).read()
strCSS = '<head><style>' + strStyle + '</style></head>'

print(strCSS)
print("<table>")
print("<tr class='th0'><th>id</th><th>name</th><th>value 1</th><th>value 2</th><th>value 3</th><th>value 4</th></tr>")
isSingle = True
for tr in table[1:] :
    print("<tr>")
    tdStyle='tdSingle0'
    if isSingle :
        tdStyle='tdSingle0'
        isSingle = False
    else :
        tdStyle='tdDouble0'
        isSingle = True
    print("<td class='" + tdStyle + "'><a href='http://www.baidu.com'>" + tr[0] + "</a></td>")
    for td in tr[1:] :
        print("<td class='" + tdStyle + "'>" + td + "</td>")
    print("</tr>")

print("</table>")


